In [1]:
# Import the world!
import os
import csv
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import random
import pandas as pd
import numpy as np

## Part Two : Entering links to pick data

In [2]:
csv = './Career_Links_bizint.csv'
df = pd.read_csv(csv)

In [3]:
df.head()

   Unnamed: 0                                              Links      Region
0           0  https://www.mycareersfuture.sg/job/senior-busi...     Central
1           1  https://www.mycareersfuture.sg/job/assistant-m...       South
2           2  https://www.mycareersfuture.sg/job/data-analys...  Islandwide
3           3  https://www.mycareersfuture.sg/job/sap-pm-maxi...  Islandwide
4           4  https://www.mycareersfuture.sg/job/business-in...     Central

In [4]:
# Opening the driver
driver = webdriver.Chrome('/Users/paklun/Desktop/materials-master/projects/project-4/chromedriver')

# Setting up lists
company=[]
title=[]
employment=[]
seniority=[]
industry=[]
salary=[]
payment=[]
description=[]
requirements=[]
count=0

# Looping through links to scrape data, impute Nan if error

for x in df.Links:
    driver.get(x)
    count +=1
    sleep(random.randint(4,6))
    print('Currently Scraping Link No.',count)
    
    try:
        company.append(driver.find_element_by_name('company').text)
    except:
        company.append(np.nan)
    try:
        title.append(driver.find_element_by_id('job_title').text)
    except:
        title.append(np.nan)    
    try:
        employment.append(driver.find_element_by_id('employment_type').text)
    except:
        employment.append(np.nan)
    try:
        seniority.append(driver.find_element_by_id('seniority').text)
    except:
        seniority.append(np.nan)
    try:
        industry.append(driver.find_element_by_id('job-categories').text)
    except:
        industry.append(np.nan)
    try:
        salary.append(driver.find_element_by_class_name('lh-solid').text)
    except:
        salary.append(np.nan)
    try:
        payment.append(driver.find_element_by_class_name('salary_type').text)
    except:
        payment.append(np.nan)      
    try:
        description.append(driver.find_element_by_id('job_description').text)
    except:
        description.append(np.nan)
    try:
        requirements.append(driver.find_element_by_id('requirements').text)
    except:
        requirements.append(np.nan)
    
    if count%10==0:
        data = pd.DataFrame({'Company':company,'Title':title,'Employment Type':employment,'Seniority':seniority,'Industry':industry,'Salary':salary,'Payment':payment,'Description':description, 'Requirements':requirements })
        result = pd.concat([df,data], axis=1,sort=False)
        result.to_csv('Career_Database_bizint.csv')
        print('Savepoint:',count)

Currently Scraping Link No. 1
Currently Scraping Link No. 2
Currently Scraping Link No. 3
Currently Scraping Link No. 4
Currently Scraping Link No. 5
Currently Scraping Link No. 6
Currently Scraping Link No. 7
Currently Scraping Link No. 8
Currently Scraping Link No. 9
Currently Scraping Link No. 10
Savepoint: 10
Currently Scraping Link No. 11
Currently Scraping Link No. 12
Currently Scraping Link No. 13
Currently Scraping Link No. 14
Currently Scraping Link No. 15
Currently Scraping Link No. 16
Currently Scraping Link No. 17
Currently Scraping Link No. 18
Currently Scraping Link No. 19
Currently Scraping Link No. 20
Savepoint: 20
Currently Scraping Link No. 21
Currently Scraping Link No. 22
Currently Scraping Link No. 23
Currently Scraping Link No. 24
Currently Scraping Link No. 25
Currently Scraping Link No. 26
Currently Scraping Link No. 27
Currently Scraping Link No. 28
Currently Scraping Link No. 29
Currently Scraping Link No. 30
Savepoint: 30
Currently Scraping Link No. 31
Currently Scraping Link No. 32
Currently Scraping Link No. 33
Currently Scraping Link No. 34
Currently Scraping Link No. 35
Currently Scraping Link No. 36
Currently Scraping Link No. 37
Currently Scraping Link No. 38
Currently Scraping Link No. 39
Currently Scraping Link No. 40
Savepoint: 40
Currently Scraping Link No. 41
Currently Scraping Link No. 42
Currently Scraping Link No. 43
Currently Scraping Link No. 44
Currently Scraping Link No. 45
Currently Scraping Link No. 46
Currently Scraping Link No. 47
Currently Scraping Link No. 48
Currently Scraping Link No. 49
Currently Scraping Link No. 50
Savepoint: 50
Currently Scraping Link No. 51
Currently Scraping Link No. 52
Currently Scraping Link No. 53
Currently Scraping Link No. 54
Currently Scraping Link No. 55
Currently Scraping Link No. 56
Currently Scraping Link No. 57
Currently Scraping Link No. 58
Currently Scraping Link No. 59
Currently Scraping Link No. 60
Savepoint: 60
Currently Scraping Link No. 61
Currently Scraping Link No. 62
Currently Scraping Link No. 63
Currently Scraping Link No. 64
Currently Scraping Link No. 65
Currently Scraping Link No. 66
Currently Scraping Link No. 67
Currently Scraping Link No. 68
Currently Scraping Link No. 69
Currently Scraping Link No. 70
Savepoint: 70
Currently Scraping Link No. 71
Currently Scraping Link No. 72
Currently Scraping Link No. 73
Currently Scraping Link No. 74
Currently Scraping Link No. 75
Currently Scraping Link No. 76
Currently Scraping Link No. 77
Currently Scraping Link No. 78
Currently Scraping Link No. 79
Currently Scraping Link No. 80
Savepoint: 80
Currently Scraping Link No. 81
Currently Scraping Link No. 82
Currently Scraping Link No. 83
Currently Scraping Link No. 84
Currently Scraping Link No. 85
Currently Scraping Link No. 86
Currently Scraping Link No. 87
Currently Scraping Link No. 88
Currently Scraping Link No. 89
Currently Scraping Link No. 90
Savepoint: 90
Currently Scraping Link No. 91
Currently Scraping Link No. 92
Currently Scraping Link No. 93
Currently Scraping Link No. 94
Currently Scraping Link No. 95
Currently Scraping Link No. 96
Currently Scraping Link No. 97
Currently Scraping Link No. 98
Currently Scraping Link No. 99
Currently Scraping Link No. 100
Savepoint: 100

In [5]:
data = pd.DataFrame({'Company':company,'Title':title,'Employment Type':employment,'Seniority':seniority,'Industry':industry,'Salary':salary,'Payment':payment,'Description':description, 'Requirements':requirements })

In [6]:
data

,Company,Title,Employment Type,Seniority,Industry,Salary,Payment,Description,Requirements
0,STREETSINE SINGAPORE PTE. LTD.,Senior Business Analyst,Full Time,Middle Management,Information Technology,"$4,000to$6,000",Monthly,Roles & Responsibilities\nSenior Business Anal...,Requirements\nRequirements:\nBachelor’s degree...
1,OAKWOOD WORLDWIDE (ASIA) PTE. LTD.,"Assistant Manager, Operations Performance Mana...",Full Time,Manager,Hospitality,NaN,,Roles & Responsibilities\nWe are looking for a...,Requirements\nWHAT WE REQUIRE\nAt least a Bach...
2,INTERNATIONAL SOS TECHNOLOGY SERVICES PTE. LTD.,Data Analyst,Full Time,Professional,Information Technology,"$6,000to$6,500",Monthly,Roles & Responsibilities\nIn our Digital Innov...,Requirements\nEducation and Experience:\nBache...
3,BLUE OCEAN SYSTEMS INFOTECH PTE. LTD.,SAP PM MAXIMO,Permanent,Middle Management,Consulting,"$6,000to$7,000",Monthly,Roles & Responsibilities\nat least one Full li...,Requirements\nat least one Full life cycle PM ...
4,DREAMSCAPE NETWORKS INTERNATIONAL PTE. LTD.,Business Intelligence Developer,Permanent,Professional,Information Technology,"$5,000to$7,000",Monthly,Roles & Responsibilities\nAs a Business Intell...,Requirements\nmyYou should have:\nA degree in ...
5,GRABTAXI HOLDINGS PTE. LTD.,Data Analyst,Full Time,Executive,Information Technology,NaN,,Roles & Responsibilities\nGet to know our Team...,Requirements\nThe must haves:\nA Bachelor's/Ma...
6,ROCHE DIAGNOSTICS ASIA PACIFIC PTE LTD,"Controller, Asia Pacific",Full Time,Executive,Healthcare / Pharmaceutical,"$5,000to$9,000",Monthly,Roles & Responsibilities\nWho we are\nAt Roche...,Requirements\nWho you are\nYou’re someone who ...
7,TECHCOM SOLUTIONS & CONSULTANCY PTE. LTD.,SAP BODS Consultant,"Contract, Full Time",Professional,"Banking and Finance, Information Technology","$5,000to$6,500",Monthly,Roles & Responsibilities\nSeeking a skilled an...,Requirements\nSeeking a skilled and experience...
8,R SYSTEMS (SINGAPORE) PTE LIMITED,Datawarehouse Consultant,Full Time,Executive,Information Technology,"$6,000to$7,000",Monthly,Roles & Responsibilities\nExperience working w...,Requirements\nGood experience in HADOOP IS REQ...
9,COMPANY UNDISCLOSED,Solution architect,"Contract, Full Time",Senior Executive,Information Technology,"$7,000to$8,500",Monthly,Roles & Responsibilities\n· Total Expe...,"Requirements\nSound knowledge of SDLC, estimat..."
10,COMPANY UNDISCLOSED,Manager,Full Time,Manager,Information Technology,"$14,000to$15,000",Monthly,Roles & Responsibilities\nCandidate should hav...,Requirements\nJob Requirements:\nBachelor degr...
11,GOOGLE ASIA PACIFIC PTE. LTD.,"Data Science Lead, Large Customer Sales - Sing...",Full Time,Executive,Information Technology,"$7,700to$15,400",Monthly,Roles & Responsibilities\nCompany overview:\nG...,Requirements\nMinimum qualifications:\n- Bache...
12,MANPOWER STAFFING SERVICES (SINGAPORE) PTE LTD,SharePoint Developer,"Contract, Full Time",Executive,Information Technology,"$6,000to$12,000",Monthly,Roles & Responsibilities\nAs a SharePoint Deve...,Requirements\nProgramming in HTML5 with JavaSc...
13,WIPRO LIMITED (SINGAPORE BRANCH),Project Manager,Permanent,Professional,Information Technology,"$8,500to$10,500",Monthly,Roles & Responsibilities\nPosition Responsibil...,Requirements\nBachelor’s degree required (mini...
14,COMPANY UNDISCLOSED,General Manager,Full Time,"Senior Management, Professional, Executive",General Management,"$14,000to$15,000",Monthly,Roles & Responsibilities\nCandidate should hav...,Requirements\nBachelor degree in Business Econ...
15,LAMINAAR AVIATION INFOTECH PTE. LTD.,Lead - Business Intelligence,Full Time,Professional,Information Technology,"$8,000to$12,000",Monthly,Roles & Responsibilities\nDesign and architect...,Requirements\nProficiency in Data Visualizatio...
16,"TURNER BROADCASTING SALES SOUTHEAST ASIA, INC","Engineer, Business Intelligence",Permanent,Executive,Information Technology,"$68,040to$83,160",Annually,Roles & Responsibilities\nThe Business Intelli...,Requirements\nEssential\n1. 4+ years solid exp...
17,SINGAPORE POWER LIMITED,Data Scientist,Full Time,Professional,Information Technology,"$4,000to$8,000",Monthly,Roles & Responsibilities\nWhy Work for Us\nWe ...,Requirements\nWhat You'll Need\nWe are looking...
18,SINGAPORE POWER LIMITED,Senior Data Scientist,Full Time,Middle Management,Information Technology,"$8,000to$14,000",Monthly,Roles & Responsibilities\nWhy Work for Us\nWe ...,Requirements\nWhat You'll Need\nWe are looking...
19,SABRE ASIA PACIFIC PTE. LTD.,HR Business Partner,Full Time,Senior Executive,Human Resources,"$84,000to$144,000",Annually,Roles & Responsibilities\nSabre is a leading t...,Requirements\nDesired Skills and Experience\nS...
20,WILHELMSEN SHIPS SERVICE (S) PTE. LTD.,Financial Analyst,"Permanent, Full Time",Fresh/entry level,Accounting / Auditing / Taxation,"$3,000to$4,500",Monthly,Roles & Responsibilities\nReview and comment o...,Requirements\nACCA/CPA/Minimum Degree in Finan...
21,FIXED & MOBILE PTE. LTD.,Head of Data Engineering,"Permanent, Full Time",Senior Management,Information Technology,"$8,000to$11,000",Monthly,Roles & Responsibilities\nTransferTo operates ...,Requirements\nEssential Experience\nMore than ...
22,COMPANY UNDISCLOSED,Developer,Full Time,Executive,Information Technology,"$9,500to$12,000",Monthly,"Roles & Responsibilities\nDevelop, deliver and...",Requirements\n Education and\nQualifications\...
23,INFOSYS CONSULTING PTE. LTD.,Business Analyst Consultant,Full Time,"Professional, Non-executive",Consulting,"$5,500to$10,000",Monthly,Roles & Responsibilities\nResponsibility\nSupp...,Requirements\nFunctional Skills:\nStakeholder ...
24,JABIL CIRCUIT (SINGAPORE) PTE. LTD.,Data Scientist,"Permanent, Full Time",Executive,"Information Technology, Manufacturing","$3,000to$6,000",Monthly,Roles & Responsibilities\nJOB SUMMARY\nThe Dat...,"Requirements\n● Advanced Statistics, o..."
25,ICON CONSULTING-GROUP PTE. LTD.,Analytics Architect,Permanent,Professional,Information Technology,"$15,000to$20,000",Monthly,Roles & Responsibilities\nSolution Architect\n...,Requirements\nDesired Skills:\nExcellent Custo...
26,STANDARD CHARTERED BANK,"Finance Manager, ITO",Full Time,"Middle Management, Manager","Accounting / Auditing / Taxation, Banking and ...","$7,500to$10,000",Monthly,Roles & Responsibilities\nKey Responsibilities...,Requirements\nKey Requirements\nDegree qualifi...
27,STREETSINE SINGAPORE PTE. LTD.,Senior Database Specialist,Full Time,Middle Management,Information Technology,"$4,000to$6,000",Monthly,Roles & Responsibilities\nDescription: Senior ...,Requirements\nSpecific skills/experience:\nBac...
28,COCA-COLA SINGAPORE BEVERAGES PTE. LTD.,Trade Analyst,"Permanent, Full Time",Executive,Marketing / Public Relations,"$2,400to$3,300",Monthly,Roles & Responsibilities\nResponsible for prov...,Requirements\nQualification Criteria\n•Minimum...
29,BRINK'S SINGAPORE PTE LTD,Sales cum Marketing Manager,Permanent,Manager,"Marketing / Public Relations , Sales / Retail",NaN,,Roles & Responsibilities\nBRINK'S SINGAPORE PT...,Requirements\nDegree holder in a related field...
...,...,...,...,...,...,...,...,...,...
70,UNIMAS CONSULTING SOLUTIONS PTE. LTD.,Senior Consultant Data Analytics,"Contract, Full Time, Internship",Middle Management,Consulting,"$6,000to$9,000",Monthly,Roles & Responsibilities\nBI/Data Analytics / ...,"Requirements\nBI/Data Analytics / FP&A, Manage..."
71,NINJA LOGISTICS PTE. LTD.,Business Intelligence Project Manager,"Permanent, Full Time","Middle Management, Professional, Senior Executive",Professional Services,"$6,000to$9,500",Monthly,Roles & Responsibilities\nNinja Van is on a mi...,Requirements\nStrong communications skills\nAb...
72,AMAZON WEB SERVICES SINGAPORE PRIVATE LIMITED,Big Data Solutions Architect,Permanent,Professional,Information Technology,"$130,000to$250,000",Annually,Roles & Responsibilities\nAmazon Web Services ...,Requirements\nBasic Qualifications: \nDeep und...
73,CPM CONSULTING PTE. LTD.,Associate Consultant,Full Time,Fresh/entry level,Information Technology,"$3,000to$4,000",Monthly,"Roles & Responsibilities\nCPM Consulting, a Ba...",Requirements\nQualifications:\nEducational bac...
74,APAR INNOSYS PTE. LTD.,Senior Datawarehouse Consultant,Contract,Executive,Information Technology,"$6,000to$8,000",Monthly,Roles & Responsibilities\nPrepare Test cases f...,"Requirements\nDegree in Statistics, Mathematic..."
75,CPM CONSULTING PTE. LTD.,Data Science Lead Consultant,Permanent,Professional,Information Technology,"$7,000to$9,000",Monthly,Roles & Responsibilities\nPrimary Responsibili...,Requirements\nQualification:\nComputer Science...
76,SAMSUNG SDS ASIA PACIFIC PTE. LTD.,Assistant Manager,Permanent,"Professional, Senior Executive",Information Technology,"$3,500to$7,000",Monthly,Roles & Responsibilities\nCompile complex data...,Requirements\nBachelor's degree in Mathematics...
77,ZALORA SOUTH EAST ASIA PTE. LTD.,Junior Merchandise Planner,"Permanent, Full Time",Junior Executive,Purchasing / Merchandising,"$3,000to$4,000",Monthly,Roles & Responsibilities\nWe are looking for a...,Requirements\nRequirements:\nEducated to Degre...
78,IKANO PTE LTD,Business Intelligence Analyst,Permanent,Middle Management,"Accounting / Auditing / Taxation, Others",NaN,,Roles & Responsibilities\nABOUT THE JOB\nWe wa...,"Requirements\nYOUR PROFILE \nYour knowledge, s..."
79,AMAZON WEB SERVICES SINGAPORE PRIVATE LIMITED,APAC Head of Enterprise Operations,Full Time,Senior Management,Information Technology,"$20,000to$30,000",Monthly,Roles & Responsibilities\nAWS is one of Amazon...,Requirements\n· 7+ years of experience in fina...
80,MIDEA ELECTRIC TRADING (SINGAPORE) CO. PTE. LTD.,Senior Sales & Marketing Manager,Full Time,"Manager, Executive, Senior Executive","Marketing / Public Relations , Sales / Retail","$5,000to$6,500",Monthly,Roles & Responsibilities\nManager of Sales & M...,Requirements\nExperience & Background\n3+ year...
81,QATAR AIRWAYS GROUP (Q.C.S.C.),Regional Cargo Business Analyst,Permanent,Executive,Travel / Tourism,"$3,500to$5,500",Monthly,Roles & Responsibilities\nAbout the Job:\nAs a...,Requirements\nAbout You:\nTo qualify for the r...
82,APAR TECHNOLOGIES PTE. LTD.,Senior Datawarehouse Consultant,Contract,Professional,Information Technology,"$6,000to$8,000",Monthly,Roles & Responsibilities\nPrepare Test cases f...,"Requirements\nDegree in Statistics, Mathematic..."
83,MONEYSMART SINGAPORE PTE. LTD.,Data Team Lead,Full Time,Manager,Information Technology,"$7,000to$12,000",Monthly,Roles & Responsibilities\nAbout the job\nMoney...,Requirements\nRequirements\n6+ years of profes...
84,ANOTECH ENERGY SINGAPORE PTE. LTD.,Senior MS Business Intelligence Software Engineer,Contract,Senior Executive,Information Technology,NaN,,Roles & Responsibilities\nAn exciting opportun...,Requirements\nQualifications and Profile\nTech...
85,ZALORA SOUTH EAST ASIA PTE. LTD.,Senior Business Intelligence Analyst,"Permanent, Full Time",Professional,Others,"$4,000to$7,000",Monthly,"Roles & Responsibilities\nIn this role, the Se...",Requirements\nMinimum Bachelor’s degree in a q...
86,ANOTECH ENERGY SINGAPORE PTE. LTD.,MS Business Intelligence Software Engineer,Contract,Executive,Information Technology,NaN,,Roles & Responsibilities\n Position\n The de...,Requirements\nQualifications and Profile\n Ma...
87,ZALORA SOUTH EAST ASIA PTE. LTD.,Senior Business Intelligence Analyst,"Permanent, Full Time",Professional,"Logistics / Supply Chain, Others","$5,000to$7,000",Monthly,"Roles & Responsibilities\nIn this role, the Se...",Requirements\nMinimum Bachelor’s degree in a q...
88,D2X EXPERTISE PTE. LTD.,Business Intelligence Analyst Developer,"Permanent, Full Time",Professional,"Customer Service, Logistics / Supply Chain","$4,000to$9,000",Monthly,Roles & Responsibilities\nWe are looking for a...,Requirements\n5+ years of experience in busine...
89,ADECCO PERSONNEL PTE LTD,Business Intelligence Software Engineer,"Contract, Full Time",Executive,Information Technology,"$5,000to$7,500",Monthly,Roles & Responsibilities\nMain responsibilitie...,Requirements\nThis position requires 5+ years ...
90,BOEHRINGER INGELHEIM ANIMAL HEALTH SINGAPORE P...,"Customer Experience Manager, Regional Operativ...",Full Time,"Middle Management, Manager","Consulting , Healthcare / Pharmaceutical","$7,400to$13,320",Monthly,Roles & Responsibilities\nTranslate Customer E...,Requirements\nBusiness orientation and experie...
91,SINGAPORE LAND AUTHORITY,"Assistant Manager / Technical Manager, GeoSpat...",Full Time,Manager,"Information Technology, Public / Civil Service","$4,000to$6,800",Monthly,Roles & Responsibilities\nAssistant Manager/ T...,NaN
92,STREETSINE SINGAPORE PTE. LTD.,Senior Data Analyst,"Permanent, Full Time","Professional, Executive",Information Technology,"$4,000to$8,000",Monthly,Roles & Responsibilities\nWe are currently loo...,Requirements\nRequirements:\nMinimum 2 years o...
93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,COMPANY UNDISCLOSED,Marketing Manager,Full Time,Manager,Marketing / Public Relations,"$5,000to$10,000",Monthly,Roles & Responsibilities\nPRIMARY FUNCTION\nPa...,Requirements\nREQUIREMENT\nEducation\nUniversi...
95,HAYS SPECIALIST RECRUITMENT PTE. LTD.,Business Intelligence Analyst,"Permanent, Contract, Full Time",Junior Executive,Information Technology,"$4,000to$5,000",Monthly,Roles & Responsibilities\nThis consultancy com...,Requirements\nExcellent communication and stak...
96,BACKOFFICE ASSOCIATES ASIA PTE. LTD.,Data Science Consultant,Full Time,Professional,Information Technology,"$7,000to$9,000",Monthly,Roles & Responsibilities\nPrimary Responsibili...,Requirements\nCandidate should possess good so...
97,BACKOFFICE ASSOCIATES ASIA PTE. LTD.,Data Science Consultant,Full Time,Professional,Information Technology,"$6,000to$8,000",Monthly,Roles & Responsibilities\nPrimary Responsibili...,Requirements\nCandidate should possess good so...
98,FIXED & MOBILE PTE. LTD.,Data Engineer,Permanent,Non-executive,Information Technology,"$4,000to$7,000",Monthly,Roles & Responsibilities\nTransferTo operates ...,Requirements\nEssential Experience\nMore than ...
99,COMPANY UNDISCLOSED,Digital Insights manager,Full Time,Manager,Others,NaN,,Roles & Responsibilities\nReporting to the Res...,Requirements\nEssential\n1. Experience in a m...

In [7]:
# result = pd.concat([df,data], axis=1,sort=False)

In [8]:
# result.to_csv('Career_Database_bizint.csv')

In [9]:
# Closes the driver
driver.close()